config/routes.rb
Rails.application.routes.draw do
	resources :categories 
	resources :lists do
		resources :accepts
	end
	 
	

			
		

	
	root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accept.rb
class Accept < ApplicationRecord
  belongs_to :list
  validates :start_d, :end_d, presence: true
  validate :end_date_after_start_date
  validate :date_need_to_be_inrange
  validate :avaliblity
  private

  def end_date_after_start_date
    return if end_d.blank? || start_d.blank?

    if end_d < start_d
      errors.add(:end_d, "must be after the start date")
    end
 end
 def date_need_to_be_inrange
 	 return if end_d.blank? || start_d.blank?
     if end_d>list.end_d || start_d<list.start_d
     	errors.add(list.start_d.to_s,"start date of the item")
     	errors.add(list.end_d.to_s,"end  date of the item")
    end
end
def avaliblity
	return if end_d.blank? || start_d.blank?
	a=list.accept.pluck(:start_d,:end_d)
	i=0
	while(i!=a.length) do
		 if start_d.between?(a[i][0],a[i][1]) || end_d.between?(a[i][0],a[i][1])
		 	errors.add(a.to_s,"already booked dates")
		 	break
		 end
		end
	end
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability_alidator.rb
class AvailabilityValidator < ActiveModel::EachValidator

  def validate_each(record, attribute, value)
    accepts = Accept.where(["id =?", accept.id])
    date_ranges = accepts.map { |b| b.start_d..b.end_d }

    date_ranges.each do |range|
      if range.include? value
        record.errors.add(attribute, "not available")
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
	#has_many :list
end

app/models/list.rb
class List < ApplicationRecord
	has_many :accept
	validates :start_d, :end_d, presence: true
end

app/controllers/accepts_controller.rb
class AcceptsController < ApplicationController
	def index
   @list=List.find(params[:list_id])
   @accept =@list.accept.all
  end
def new

   @list=List.find(params[:list_id])
   @accept =@list.accept.new
 		
end
 def show
 	@list=List.find(params[:list_id])
   @accept =@list.accept.find(params[:id])
  end
def create
	@list=List.find(params[:list_id])
  	@accept = @list.accept.new(accept_params)
   if @accept.save
    redirect_to  list_accept_path(params[:list_id],@accept)
  else
    render 'new'
end
end

private
  def accept_params
    params.require(:accept).permit(:list_id,:start_d,:end_d)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
		def index
    @lists = List.all
  end
def new
  @list = List.new
end
 def show
    @list = List.find(params[:id])
   @category=Category.find(@list.categorymain_id)
  end

def create
  @list = List.new(list_params)
   @list.save
    redirect_to @list
  
end
 def destroy
    @list = List.find(params[:id])
    @list.destroy
 
    redirect_to lists_path
  end
private
  def list_params
    params.require(:list).permit(:name,:categorymain_id,:cost_per_day,:trans,:start_d,:end_d)
  end
end

  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/accepts_helper.rb
module AcceptsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datepickerHelper.rb
module datepickerHelper

def datepicker_input form, field
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'DD-MM-YYYY'
    end
  end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accepts/index.html.erb
<h1><center>Booked Item's Details</h1>
<table>
  <tr>
    <th>startdate</th>
    <th>enddate</th> 
    <th colspan="3"></th>
  </tr>
 
  <% @list.accept.each do |accept| %>
    <tr>
      <td><%= accept.start_d %></td> 
      <td><%= accept.end_d %></td>
      <td><%= accept.list_id %></td>
   </tr>
  <% end %>

app/views/accepts/new.html.erb
<h1><center>Book Your Item</h1>
<%= form_for :accept, url: list_accepts_path do |f| %>
 <% if @accept.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@accept.errors.count, "error") %> prohibited
        this accept from being saved:
      </h2>
      <ul>
        <% @accept.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>Already booked dates
  <%=@list.accept.pluck(:start_d,:end_d) %></p>
    <p>
      <%= f.hidden_field :list_id %>
  </p>    
   <p>
    <%= f.label :start_date%><br>
     <%= f.date_field :start_d%>  </p>
   <p>
    <%= f.label :end_date %><br>
    <%= f.date_field :end_d,:autocomplete => :off%>
  </p>
  
  <p>

    <%= f.submit %>
  </p>
<% end %>

app/views/accepts/show.html.erb
 <p>
  <strong>start date:</strong>
  <%= @accept.start_d %>
</p>
<p>
  <strong>end date:</strong>
  <%= @accept.end_d %>
</p>
<p>
  <strong>list_id:</strong>
  <%= @accept.list_id %>
</p>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myweb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %> 
 <p>
    <%= f.label :name %><br>
    <%= f.text_field :name,:autocomplete => :off%>
  </p>
  <p>
    <%= f.label :type_of_item %><br>
    <%= f.select "categorymain_id", options_from_collection_for_select(Category.all, :id, :name), {:class=>'form-control', :prompt => ''}  %>  
      </p>
  
   <p>
    <%= f.label :Transaction_Type%><br>
    <%= f.select(:trans, [ 'Lend', 'Borrow'], {}, { :class => 'form-control'}) %>
  </p>
  <p>
    <%= f.label :cost_per_day %><br>
    <%= f.text_field :cost_per_day, :autocomplete => :off%>
  </p>
   <p>
    <%= f.label :start_date%><br>
   <%= f.text_field :start_d,:autocomplete => :off%>
  </p>
   <p>
    <%= f.label :end_date %><br>
    <%= f.text_field :end_d,:autocomplete => :off%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/lists/index.html.erb

<h1>Listing lists</h1>
<h1>Hello, Rails!</h1>
<%= link_to 'My socio', controller: 'lists' %>
<%= link_to 'New list', new_list_path %> 
<table>
  <tr>
    <th>Name</th>
    <th>typeofitem</th> 
    <th>cost_per_day</th>
    <th>transaction_type</th> 
    <th>startdate</th>
    <th>enddate</th> 
    <th colspan="3"></th>
  </tr>
 
  <% @lists.each do |list| %>
    <tr>
      <td><%= list.name %></td>
      <td><%= list.categorymain_id %></td>
      <td><%= list.cost_per_day %></td> 
      <td><%= list.trans %></td>
      <td><%= list.start_d %></td> 
      <td><%= list.end_d %></td>
      <td><%= link_to 'Book yout item', new_list_accept_path(list.id) %> </td>
      <td><%= link_to 'Destroy',list_path(list),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
   </tr>
  <% end %>

app/views/lists/new.html.erb
<h1><center>Welcome to socio</h1>

<%= form_for :list, url: lists_path do |f| %>
 <p>
    <%= f.label :name %><br>
    <%= f.text_field :name,:autocomplete => :off%>
  </p>
  <p>
    <%= f.label :type_of_item %><br>
    <%= f.select "categorymain_id", options_from_collection_for_select(Category.all, :id, :name), {:class=>'form-control', :prompt => 'select any one' }  %>  
      </p>
  
   <p>
    <%= f.label :Transaction_Type%><br>
    <%= f.select :trans,[ 'Lend', 'Borrow'],{},:class => 'form-control' %>
  </p>
  <p>
    <%= f.label :cost_per_day %><br>
    <%= f.text_field :cost_per_day, :autocomplete => :off %>
  </p>
   <p>
    <%= f.label :start_date%><br>
   <%= f.date_field :start_d,:autocomplete => :off%>
  </p>
   <p>
    <%= f.label :end_date %><br>
    <%= f.date_field :end_d,:autocomplete => :off%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

x

app/views/lists/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>
 
<p>
  <strong>type of item:</strong>
      <%= @category.name %>
</p>
 <p>
  <strong>cost per day:</strong>
  <%= @list.cost_per_day %>
</p>
 <p>
  <strong>transaction type:</strong>
  <%= @list.trans%>
</p>
 <p>
  <strong>start date:</strong>
  <%= @list.start_d %>
</p>
<p>
  <strong>end date:</strong>
  <%= @list.end_d %>
</p>
 

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>